[colors]
ansi = [
    '#1a1122',
    '#e8a4eb',
    '#8C7AB8', #field name in go
    '#9d7abf', #variable name
    '#af76b5',
    '#947da7',
    '#baacc7',
    '#e6e1ea',
]
background = '#1d1d1d'
brights = [
    '#5b5a5c', #selection
    '#e5e1eb',
    '#91b065', #string color
    '#f3a447', #type color
    '#b26ee1', #syntax lang color and cursor in editor
    '#c8a1e9',
    '#91b065',
    '#f3a447',
]
cursor_bg = '#8b8198'
cursor_border = '#8b8198'
cursor_fg = '#8b8198'
foreground = '#dbd5e2'
selection_bg = '#8b8198'
selection_fg = '#fbf1f2'

[colors.indexed]

[metadata]
author = 'Axl'
name = 'Purple'
