[shell]
program = "zsh"
args = ['-l']

[window]
decorations = "None"
padding = { x = 10, y = 8 }
opacity = 0.8
blur = true

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 10.0

[colors.primary]
background = "#050505"

# [keyboard]
# bindings = [
# 	{ key = "1", mods = "ALT", chars = "\u0002\u0031" },
# 	{ key = "2", mods = "ALT", chars = "\u0002\u0032" },
# 	{ key = "3", mods = "ALT", chars = "\u0002\u0033" },
# 	{ key = "4", mods = "ALT", chars = "\u0002\u0034" },
# 	{ key = "5", mods = "ALT", chars = "\u0002\u0035" },
# 	{ key = "6", mods = "ALT", chars = "\u0002\u0036" },
# 	{ key = "7", mods = "ALT", chars = "\u0002\u0037" },
# 	{ key = "8", mods = "ALT", chars = "\u0002\u0038" },
# 	{ key = "9", mods = "ALT", chars = "\u0002\u0039" },
# 	{ key = "0", mods = "ALT", chars = "\u0002\u0030" },
# 	{ key = "e", mods = "ALT", chars = "\u0002%" },
# 	{ key = "e", mods = "ALT|SHIFT", chars = "\u0002\"" },
# 	{ key = "w", mods = "ALT", chars = "\u0002w" },
# 	{ key = "Left", mods = "ALT|SHIFT", chars = "\u0002l" },
# 	{ key = "Right", mods = "ALT|SHIFT", chars = "\u0002h" },
# 	{ key = "Up", mods = "ALT|SHIFT", chars = "\u0002k" },
# 	{ key = "Down", mods = "ALT|SHIFT", chars = "\u0002j" },
# ]
