[shell]
program = "zsh"
args = ['-l']

[window]
decorations = "None"
padding = { x = 10, y = 8 }
opacity = 1
blur = true

[font]
# normal = {family = "JetBrainsMono NF ExtraBold"}
normal = {family = "JetBrainsMono NF SemiBold"}
size = 10.0

[colors.primary]
# background = "#050505"
background = "#0d0d0d"
dim_foreground = "#908caa"
bright_foreground = "#e0def4"

[colors.cursor]
text = "#e0def4"
cursor = "#524f67"

[colors.vi_mode_cursor]
text = "#e0def4"
cursor = "#524f67"

[colors.search.matches]
foreground = "#908caa"
background = "#26233a"

[colors.search.focused_match]
foreground = "#191724"
background = "#ebbcba"

[colors.hints.start]
foreground = "#908caa"
background = "#1f1d2e"

[colors.hints.end]
foreground = "#6e6a86"
background = "#1f1d2e"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#e0def4"
background = "#1f1d2e"

[colors.selection]
text = "#e0def4"
background = "#403d52"

[colors.normal]
black = "#26233a"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

[colors.bright]
black = "#6e6a86"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

[colors.dim]
black = "#6e6a86"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

# [keyboard]
# bindings = [
# 	{ key = "1", mods = "ALT", chars = "\u0002\u0031" },
# 	{ key = "2", mods = "ALT", chars = "\u0002\u0032" },
# 	{ key = "3", mods = "ALT", chars = "\u0002\u0033" },
# 	{ key = "4", mods = "ALT", chars = "\u0002\u0034" },
# 	{ key = "5", mods = "ALT", chars = "\u0002\u0035" },
# 	{ key = "6", mods = "ALT", chars = "\u0002\u0036" },
# 	{ key = "7", mods = "ALT", chars = "\u0002\u0037" },
# 	{ key = "8", mods = "ALT", chars = "\u0002\u0038" },
# 	{ key = "9", mods = "ALT", chars = "\u0002\u0039" },
# 	{ key = "0", mods = "ALT", chars = "\u0002\u0030" },
# 	{ key = "e", mods = "ALT", chars = "\u0002%" },
# 	{ key = "e", mods = "ALT|SHIFT", chars = "\u0002\"" },
# 	{ key = "w", mods = "ALT", chars = "\u0002w" },
# 	{ key = "Left", mods = "ALT|SHIFT", chars = "\u0002l" },
# 	{ key = "Right", mods = "ALT|SHIFT", chars = "\u0002h" },
# 	{ key = "Up", mods = "ALT|SHIFT", chars = "\u0002k" },
# 	{ key = "Down", mods = "ALT|SHIFT", chars = "\u0002j" },
# ]
