theme = "base16_transparent"

[editor]
line-number = "relative"
bufferline = "multiple"

[keys.normal]
tab = "goto_next_buffer"
S-tab = "goto_previous_buffer"
"^" = "goto_line_start"
"$" = "goto_line_end_newline"
"C->" = "jump_forward"
"C-<" = "jump_backward"

[keys.normal.space]
"/" = "toggle_comments"

[keys.normal.g]
"/" = "global_search"

[keys.normal.";"]
f = "file_picker"
F = "file_picker_in_current_directory"
b = "buffer_picker"

[keys.normal."]"]
c = "goto_next_change"
C = "goto_last_change"
g = "goto_next_comment"


[keys.normal."["]
c = "goto_prev_change"
C = "goto_first_change"
g = "goto_prev_comment"

